package adventofcode.y2024

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

internal class Day08Test {

    @Test
    fun solvePartOne() {
        assertEquals(14, Day08.solvePartOne(input))
    }

    @Test
    fun solvePartTwo() {
        assertEquals(34, Day08.solvePartTwo(input))
    }

    val input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

}