package adventofcode.y2025

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

internal class Day07Test {

    @Test
    fun solvePartOne() {
        assertEquals(21, Day07.solvePartOne(input))
    }

    @Test
    fun solvePartTwo() {
        assertEquals(40, Day07.solvePartTwo(input))
    }

    private val input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""
}